# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessenger.proto\x12\tmessenger\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"G\n\x0f\x44\x65layedResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12#\n\x07request\x18\x02 \x03(\x0b\x32\x12.messenger.Request2\x95\x02\n\tMessenger\x12\x39\n\x0eSimpleResponse\x12\x12.messenger.Request\x1a\x13.messenger.Response\x12>\n\x11StreamingResponse\x12\x12.messenger.Request\x1a\x13.messenger.Response0\x01\x12\x44\n\x10RequestStreaming\x12\x12.messenger.Request\x1a\x1a.messenger.DelayedResponse(\x01\x12G\n\x18\x42idirectionallyStreaming\x12\x12.messenger.Request\x1a\x13.messenger.Response(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=56
  _globals['_RESPONSE']._serialized_start=58
  _globals['_RESPONSE']._serialized_end=85
  _globals['_DELAYEDRESPONSE']._serialized_start=87
  _globals['_DELAYEDRESPONSE']._serialized_end=158
  _globals['_MESSENGER']._serialized_start=161
  _globals['_MESSENGER']._serialized_end=438
# @@protoc_insertion_point(module_scope)
